### ISSUE TITLE
Is it possible to drag and drop events?

### ISSUE THREAD

**Issue by Jarmo-Baltzar** [YogliB/svelte-fullcalendar#185]
Hi , nice work with the wrapper, but how do i configure additional plugins like draggable and droppable ?

**Comment by Jarmo-Baltzar** [comment]
I thiink i figured it out :)

**Comment by YogliB** [comment]
@Jarmo-Baltzar 
Will a Draggable component help?

Using it will be something like:
```html
<Draggable>
    <div data-event='{ "title": "my event", "duration": "02:00" }'>drag me</div>
</Draggable>
```
