### ISSUE TITLE
How to use Svelte's reactivity in events function?

### ISSUE THREAD

**Issue by frederikhors** [YogliB/svelte-fullcalendar#586]
Using this project I realized that it would be very useful to have a way to use Svelte's reactivity in FullCalendar's method `options.events` (as a function) https://fullcalendar.io/docs/events-function.

What do you think about it?

**Comment by YogliB** [comment]
I don't think I understand what you're trying to achieve, can you please expand on that?

**Comment by YogliB** [comment]
@frederikhors 
I'm closing this for now, reopen it if it's still an issue.
