### ISSUE TITLE
~10KB of `preact` in final bundle. Why?

### ISSUE THREAD

**Issue by frederikhors** [YogliB/svelte-fullcalendar#690]
Analyzing my final bundle I can see there are ~10KB of `preact`. **Why?**

![image](https://user-images.githubusercontent.com/41120635/113196638-0567b680-9264-11eb-800c-29c67d5f3264.png)

**Comment by frederikhors** [comment]
https://github.com/fullcalendar/fullcalendar/issues/6232

**Comment by YogliB** [comment]
Well, it's built with Preact (and not Svelte unfortunately).
