### ISSUE TITLE
locale setting partly working in sveltekit

### ISSUE THREAD

**Issue by erikbent** [YogliB/svelte-fullcalendar#738]
I have the following code in index.svelte of a new sveltekit project. The ```const common=``` line is added to prevent the isHiddenDay error.
The day view has the translated month and weekday in the title (16 mei 2021, zondag) but the text **today**, **month**, **week**, **day**, **all-day** are not translated.
```
<script>
	import { onMount } from 'svelte'
	import FullCalendar from 'svelte-fullcalendar'
	
	const options = {
		initialView: "timeGridDay",
		plugins: [],
		locale: 'nl',
		headerToolbar: {
			left: 'prev,next today',
			center: 'title',
			right: 'dayGridMonth,timeGridWeek,timeGridDay',
		},
	};

	onMount(async () => {
		const common = (await import('@fullcalendar/common')).default
		const locale = (await import('@fullcalendar/core/locales/nl')).default
		options.plugins = [
			(await import('@fullcalendar/daygrid')).default,
			(await import('@fullcalendar/timegrid')).default,
		]
	});
</script>

<FullCalendar {options} />
```

**Comment by YogliB** [comment]
Try doing:

```javascript
	onMount(async () => {
		const common = (await import('@fullcalendar/common')).default
		const locale = (await import('@fullcalendar/core/locales/nl')).default
		options = {
                    ...options,
                    locale,
                    plugins: [
			(await import('@fullcalendar/daygrid')).default,
			(await import('@fullcalendar/timegrid')).default,
		    ]
                };
	});
```

**Comment by skwasha** [comment]
Is this working with sveltekit at all? I saw there was an example app, but it's using an unreleased version of the package. Is that because there are kit related changes upcoming?

**Comment by YogliB** [comment]
I didn't manage to get it working, [this is the issue](https://github.com/fullcalendar/fullcalendar/issues/6371) that I'm currently having.

I think it's because of Vite's [Async Chunk Loading Optimization](https://vitejs.dev/guide/features.html#async-chunk-loading-optimization) that makes the FullCalendar chunks load out of order.

**Comment by skwasha** [comment]
I'm sorry - I should have updated my comment. You can add the following to your `svelte.config.js` as a workaround:
```
const config = {
  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte',
    vite: {
      optimizeDeps: {
        include: ['svelet-fullcalendar'],
      },
    },
  },
}
```

**Comment by YogliB** [comment]
tried the workaround, still getting the same issue...

**Comment by YogliB** [comment]
Can you try again with the latest version (1.1.1)?
