### ISSUE TITLE
FullCalendar doesn't play well with SvelteKit

### ISSUE THREAD

**Issue by YogliB** [YogliB/svelte-fullcalendar#800]
non-working example: https://github.com/YogliB/svelte-fullcalendar/tree/master/examples/kit

I didn't manage to get it working, [this is the issue](https://github.com/fullcalendar/fullcalendar/issues/6371) that I'm currently having.

I think it's because of Vite's [Async Chunk Loading Optimization](https://vitejs.dev/guide/features.html#async-chunk-loading-optimization) that makes the FullCalendar chunks load out of order.

**Comment by Masatoshi** [comment]
We should add '@fullcalendar/core' to devDependencies and include it from vite.
Because vite can not bundle any packages from svelte-fullcalendar's dependencies.


**svelte.config.js**
```
vite: {
	optimizeDeps: {
		include: ['@fullcalendar/core']
	}
}
```
**package.json**
```
"devDependencies": {
		"@fullcalendar/core": "^5.8.0",
```

**Comment by YogliB** [comment]
I'll try this, but you're welcome to PR this if you want to give it a go.

**Comment by iandoesallthethings** [comment]
Has there been any movement on this? I see there's a pull request, but I'm still getting `Please import the top-level fullcalendar lib before attempting to import a plugin.` even after including @fullcalendar/core in optimizeDeps.

Thanks!

**Comment by YogliB** [comment]
Still haven't been able to make it work, and I tried every piece of advice I got...

**Comment by ka1to1** [comment]
If you're on vite you can fix it by adding `@fullcalendar/core` to `rollupDedupe` and `include`

```js
export default defineConfig({
    rollupDedupe: ['svelte', '@fullcalendar/common'],
    optimizeDeps: {
          include: ['@fullcalendar/common'],
    }
});
```

**Comment by pheuter** [comment]
Installing `@fullcalendar/common` in my project's dependencies and adding the following config to `vite.config.js` worked for me:

```js
optimizeDeps: {
  include: ['@fullcalendar/common']
},
resolve: {
  dedupe: ['@fullcalendar/common']
},
```

**Comment by lmcardle** [comment]
what worked for me, without using this module, was the following:

```
<script>
	import { onMount } from 'svelte';
	import { Calendar } from '@fullcalendar/core';
	import dayGridPlugin from '@fullcalendar/daygrid';

	let calendarEl;
	let calendar;

	onMount(async () => {
		await import('@fullcalendar/core/vdom');
		calendar = new Calendar(calendarEl, {
			plugins: [dayGridPlugin],
			initialView: 'dayGridMonth'
		});
		calendar.render();
	});
</script>

<div bind:this={calendarEl} />
```

**Comment by YogliB** [comment]
> what worked for me, without using this module, was the following:
> 
> ```
> <script>
> 	import { onMount } from 'svelte';
> 	import { Calendar } from '@fullcalendar/core';
> 	import dayGridPlugin from '@fullcalendar/daygrid';
> 
> 	let calendarEl;
> 	let calendar;
> 
> 	onMount(async () => {
> 		await import('@fullcalendar/core/vdom');
> 		calendar = new Calendar(calendarEl, {
> 			plugins: [dayGridPlugin],
> 			initialView: 'dayGridMonth'
> 		});
> 		calendar.render();
> 	});
> </script>
> 
> <div bind:this={calendarEl} />
> ```

That's exactly what I did 🙂

**Comment by lmcardle** [comment]
but then as soon as i install and add a different plugin, the error comes back. 👎

**Comment by lmcardle** [comment]
hmm, even if i back out the changes with adding the new plugin, '@fullcalendar/interaction', the error persists. I wonder if svelte's cache is hosing this.

**Comment by YogliB** [comment]
I think it's Vite's cache, when you add a new npm module Vite is bundling it in a certain way, and sometimes it takes a moment for SvelteKit to catch up.

**Comment by lmcardle** [comment]
@YogliB did you ever figure out a solution to the apparent caching issue. I am able to get this working on a new app, but the moment I add additional plugins it blows up.

**Comment by Masatoshi** [comment]
YogliB is right.
vite's cache and load modules order do affect.
So we have to tell vite dependencies properly.

**Comment by lmcardle** [comment]
> So we have to tell vite dependencies properly.

any idea how to do that?

**Comment by YogliB** [comment]
This usually resolves itself by saving the file and refreshing the browser, which refreshes the server.
If this doesn't work, try stopping the server and re-starting it.

**Comment by TheophileMot** [comment]
@YogliB The package still seems broken with SvelteKit. I've tried using it in my own project, in the SvelteKit sample template, as well as the example in the fullcalendar repo, and I get the following error each time:

```
svelte-fullcalendar doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

10:15:31 p.m. [vite] Error when evaluating SSR module /node_modules/preact/compat/dist/compat.module.js?v=39414b8c:
ReferenceError: __vite_ssr_import_1__ is not defined
    at eval (/node_modules/preact/compat/dist/compat.module.js?v=39414b8c:11:712)
    at async instantiateModule (.../svelte-fullcalendar/examples/kit/node_modules/vite/dist/node/chunks/dep-5496817b.js:67449:9)
    ```
 
I'm not sure what this means exactly.

**Comment by YogliB** [comment]
@TheophileMot 
can you please open a new issue so we can track this?

**Comment by TheophileMot** [comment]
@YogliB Yes indeed: https://github.com/YogliB/svelte-fullcalendar/issues/804

**Comment by devShamim** [comment]
Just import @fullcalendar/core/vdom before you import svelte-fullcalendar and other fullcalendar plugins. Like this: 
`import '@fullcalendar/core/vdom';`
`import FullCalendar from 'svelte-fullcalendar';`
`import daygridPlugin from '@fullcalendar/daygrid';`

I am using this version (^2.0.0-beta.0) of svelte-fullcalendar along with **vite-4.0.1**
