### ISSUE TITLE
@fullcalendar/icalendar plugin seems broken?

### ISSUE THREAD

**Issue by sbutler-gh** [YogliB/svelte-fullcalendar#802]
When I try installing @fullcalendar/icalendar to import ical formats into FullCalendar in a SvelteKit app, I get the following error:

```
ICAL is not defined
ReferenceError: ICAL is not defined
    at node_modules/ical.js/build/ical.js (http://localhost:3000/node_modules/.vite/chunk-MWROEMAF.js?v=d2a4f7e5:9:12)
    at __require (http://localhost:3000/node_modules/.vite/chunk-B7LZDY4N.js?v=d2a4f7e5:41:44)
    at http://localhost:3000/node_modules/.vite/@fullcalendar_icalendar.js?v=d2a4f7e5:16:23
 ```
 
Any thoughts on a fix?

**Comment by YogliB** [comment]
can you link a reproduction?

**Comment by sbutler-gh** [comment]
> can you link a reproduction?

Here's a repo reproducing the error (https://github.com/sbutler-gh/icalendar-bug).  To reproduce:

1. Install the repository locally
2. `npm run install`
3. `npm run dev`

When I navigate to `localhost:3000`, the browser shows:

```
ICAL is not defined
ReferenceError: ICAL is not defined
    at node_modules/ical.js/build/ical.js (http://localhost:3000/node_modules/.vite/@fullcalendar_icalendar.js?v=6fbf720c:15:12)
    at __require (http://localhost:3000/node_modules/.vite/chunk-OZKD6XBJ.js?v=6fbf720c:9:44)
    at http://localhost:3000/node_modules/.vite/@fullcalendar_icalendar.js?v=6fbf720c:5124:24
    ```

**Comment by YogliB** [comment]
i'm still trying to figure it out, but it seems more like a Vite problem than a FullCalendar issue, not sure yet how to solve it...

**Comment by notKamui** [comment]
The plugin doesn't seem to work with a rollup config either.
I get a similar error : `Uncaught ReferenceError: assignment to undeclared variable ICAL`

**Comment by notKamui** [comment]
Well the problem actually comes from a depency : ical.js 

Here's a quick fix you can do yourself : https://github.com/mozilla-comm/ical.js/issues/488

**Comment by sbutler-gh** [comment]
Thanks @notKamui. Can you share what exactly the fix is, and where exactly to insert it? I wasn't 100% sure from the other issue you linked. Also, huge thanks for getting into this and bringing some progress!

**Comment by notKamui** [comment]
Hey @sbutler-gh ! Honestly I almost pulled all my hair out yesterday haha.

To 'fix' the problem, once the library is installed (with npm install for example), you need to find the ical.js module (should be located in `node_modules/ical.js/build/ical.js`) 

You should be presented with the snipped I showed in the issue I linked before. If that's the case, you just need to add `var ICAL;` at the very beginning of the file.

Yeah, it's very hacky. To make that fix a bit more permanent, you can create a small postinstall script to edit the file automatically after each `npm install`.

To do so, put your js script (let's call it postinstall.js) in the same level as your package.json file, and in the scripts object of said file, add `"postinstall": "node postinstall.js"`

**Comment by YogliB** [comment]
@notKamui 
great catch! did you try to PR this in ICAL?

**Comment by notKamui** [comment]
> great catch! did you try to PR this in ICAL?

Thing is, the current master branch over there already has the fix ! They just didn't push a new version on npm yet (the last one dates 1 April 2020, the irony)

So we really do just have to wait.

> can this issue be closed?

Yes indeed ; however, i feel like, at least for now, this notice should be somewhere in the readme (probably at the top), along with the hot fix i provided above. I'll give the actual script just in a second.

**Comment by notKamui** [comment]
@sbutler-gh @YogliB to recapitulate (so that you can put it somewhere) :

In case you want to use the fullcalendar/icalendar pluggin, an issue might arise in projects where modules or strict mode are enabled (so, incidentally, with Svelte), and is caused by a dependency of fullcalendar (which is ical.js).

It is due to the fact that they assign a variable without declaring it.

A possible hotfix would be this :

- Create a `postinstall.js` file at the same level as your `package.json`, with the following content :
```js
const fs = require('fs');

fs.readFile('node_modules/ical.js/build/ical.js', 'utf8', (err, data) => {
    if (err) {
        throw err
    } else {
        if (data.startsWith("let ICAL;")) return;
        fs.writeFile('node_modules/ical.js/build/ical.js', "let ICAL;\n" + data, (err) => {
            if (err) throw err;
        });
    }
});
```

- add the following run script to your `package.json`:
```json
{
    ...,
    "scripts": {
        "postinstall": "node postinstall",
        ...
    },
    ...
}
```

This will patch the library after each `npm install`

**Comment by YogliB** [comment]
@notKamui 
Thanks for clearing things up!

about leaving a notice, it doesn't make sense to me, since this is just a wrapper around FullCalendar and has nothing to do with ICal...
