### ISSUE TITLE
Version mismatch with FullCalendar

### ISSUE THREAD

**Issue by TheophileMot** [YogliB/svelte-fullcalendar#805]
@YogliB 

It looks like `svelte-fullcalendar` calls for version `5.0.0` of FullCalendar. However, FullCalendar's latest version is `5.10.1`, and there is a [known problem](https://github.com/fullcalendar/fullcalendar/issues/6370) when there are multiple instances of the `@fullcalendar/common` package present in the same build.

I've tried manually changing the version to `5.10.1` in `/node_modules/svelte-fullcalendar/package.json`, but still get the problem.

**Comment by YogliB** [comment]
I tried avoiding releasing a new version every time FullCalendar updates but it might have back-fired.
The solution might be using FullCalendar as a peer dependency, and it'll be a breaking change...

**Comment by YogliB** [comment]
hey, i published an experimental version, where FullCalendar is a peerDependency, can you try it?
just: `pnpm add -D svelte-fullcalendar@experimental`

**Comment by YogliB** [comment]
On a new FullCalendar version release a new breaking change will be made to this package and core fullcalendar packages will be peer dependencies.
