### ISSUE TITLE
dateProfileGenerator is undefined 

### ISSUE THREAD

**Issue by mylastore** [YogliB/svelte-fullcalendar#848]
Using the calendar with SvelteKit I get this error and the calendar won't render. 

` "svelte": "^3.44.2",
 @sveltejs/kit": "^1.0.0-next.168
 @sveltejs/adapter-node": "^1.0.0-next.55
`

`Uncaught (in promise) TypeError: dateProfileGenerator is undefined [DaySeriesModel.ts:25:10]`

**Comment by mylastore** [comment]
I also try running the example/kit provided as-is no changes and got this error:

`8:57:57 AM [vite] Error when evaluating SSR module /node_modules/preact/compat/dist/compat.module.js?v=8d6f2a7a:
ReferenceError: __vite_ssr_import_1__ is not defined
    at eval (/node_modules/preact/compat/dist/compat.module.js?v=8d6f2a7a:11:712)
    at async instantiateModule (/Users/oscarquinteros/Downloads/svelte-fullcalendar-main/examples/kit/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:9)
8:57:57 AM [vite] Error when evaluating SSR module /node_modules/@fullcalendar/core/vdom.js:
`

**Comment by YogliB** [comment]
Hey, @mylastore  👋
I just released a new beta version, and it would be great if you would read the updated README and try it out.

**Comment by vhscom** [comment]
@mylastore I've seen the error you provided and was successful at avoiding it with the latest beta. Note initial set-up no longer requires use of dynamic imports so you can get everything working without `onMount`.

**Comment by YogliB** [comment]
Yeah, i'll make sure to update the docs/example if i haven't done this already.

 You could PR this if you'd like :)

**Comment by YogliB** [comment]
If everything goes well, the stable version will be released in a month or so.
