### ISSUE TITLE
Server-Side Rendering

### ISSUE THREAD

**Issue by vhscom** [YogliB/svelte-fullcalendar#853]
Add proper server-side rendering support so we can serve HTML to the browser built on the server-side. Without it only the data used to power the calendar can be fetched server-side, resulting in a distinct flicker effect as illustrated here:

https://user-images.githubusercontent.com/97140109/160580682-96cc368d-958e-4fa6-b983-c5f5e300e467.mp4

**Comment by YogliB** [comment]
thanks for opening the issue! 🙂 

from what I know, not all plugins support server-side rendering (they rely on the `window` object), but if you have any idea on how we can improve this, feel free to make a contribution!

**Comment by vhscom** [comment]
I was thinking we could use this as an anchor to send issues upstream and define the ideal state. But no worries.

**Comment by YogliB** [comment]
what do you mean by upstream?

**Comment by vhscom** [comment]
Upstream means with FullCalendar, just as you suggested. With the new beta you released it'll be easier to create a reduced test case their developers can use to try and address the issue _upstream_. 🙂
