### ISSUE TITLE
error "Cannot read properties of undefined (reading 'isHiddenDay')

### ISSUE THREAD

**Issue by mvolkmann** [YogliB/svelte-fullcalendar#868]
I haven't been able to get the most basic example to work.
I get the error in the subject.
This seems to be a known issue in full calendar itself.
See https://github.com/fullcalendar/fullcalendar/issues/6370
Is there a way to work around this in svelte-fullcalendar?

**Comment by mvolkmann** [comment]
Ah, I think I solved it. I needed to restart my local server after modifying `svelte.config.js` to add the dedupe configuration
for `@fullcalendar/common`.

**Comment by psociety** [comment]
Leaving this for google.
In my case i'm not using sveltekit/kit. And the changes listed didn't work, so i patched it like this:
`svelte.config.js` -> created a "plugin" named `patchSvelte()`
```js
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { defineConfig } from 'vite';

function patchSvelte() {
    return {
      name: 'svelte:patch_fullcalendar',
      config(cfg) {
        return {
            resolve: {
                dedupe: ['@fullcalendar/common']
            },
            optimizeDeps: {
                include: ['@fullcalendar/common']
            }
        };
      },
    }
}

export default defineConfig({
    server: {
        port: 5000,
    },
    plugins: [svelte(), patchSvelte()]
});
```
