### ISSUE TITLE
day boxes missing

### ISSUE THREAD

**Issue by mvolkmann** [YogliB/svelte-fullcalendar#869]
The screenshot below shows what I'm seeing. When I inspect the DOM I see that the calendar is rendered by a table element. It has a thead, but no tbody where I expected to see the boxes for each day in the month. Is there something more I need to do than is shown in the getting started instructions to get those to appear?

I have the following plugins installed: daygridPlugin, timegridPlugin, and interactionPlugin.

Here is my options object that I copied from the working example link:

```js
  let options: CalendarOptions = {
    dateClick: handleDateClick,
    droppable: true,
    editable: true,
    events: [
      // initial event data
      {title: 'New Event', start: new Date()}
    ],
    initialView: 'dayGridMonth',
    plugins: [daygridPlugin, timegridPlugin, interactionPlugin],
    headerToolbar: {
      left: 'prev,next today',
      center: 'title',
      right: 'dayGridMonth,timeGridWeek,timeGridDay'
    },
    height: '100%',
    weekends: true
  };
```

![Screen Shot 2022-04-17 at 9 42 26 AM](https://user-images.githubusercontent.com/79312/163719556-3a68dd40-049f-4377-bdfa-f9dee9e7c906.png)

**Comment by vhscom** [comment]
I'd start by peeling back the plugins one by one as well as simplifying the config as much as possible until you find the point at which the issue begins to determine where the issue lays. There's an 82% chance it's a full calendar issue, a 10% chance of an integration issue and the rest I'll leave to your imagination.

Also, when posting issues, please note it's very difficult to debug without a minimum reproduction. If you have public code in a repository you could share demonstrating the issue, it's likely you will receive help faster than if not provided.

**Comment by mvolkmann** [comment]
I found the issue. It was the option `height: '100%'` that I copied from the example here: https://github.com/YogliB/svelte-fullcalendar/blob/d92fe3580f1323a1921ecfecb103993728f82589/examples/kit/src/routes/index.svelte#L22
Once I removed that, the day boxes rendered correctly. I wonder how that example is able to work with that option.

**Comment by vhscom** [comment]
Ah. Was the display issue you saw while running the example locally, or modeling the example styles?

**Comment by mvolkmann** [comment]
I was running my code locally. Does it make sense why adding `height: '100%'` would cause it to not even render the `tbody` part of the table? It wasn't just a styling issue.

**Comment by vhscom** [comment]
Not really, no. I do see `height` is a valid option defined by FullCalendar in the `CalendarOptions` type definitions. Intuition tells me it's not related to this Svelte wrapper component. Is there something that leads you to believe the issue only occurs with Svelte FullCalendar?

**Comment by vhscom** [comment]
Not really, no. I do see `height` is a valid option defined by FullCalendar in the `CalendarOptions` type definitions. Intuition tells me it's not related to this Svelte wrapper component though. Is there something in particular that leads you to believe the issue only occurs with Svelte FullCalendar?

**Comment by YogliB** [comment]
It seems like a CSS issue, `height: 100%` means that FC would take 100% of it's parent's height, and in the example the parent Div has the flex-grow property that sets its height.
