### ISSUE TITLE
Calendar is not SSR compatible

### ISSUE THREAD

**Issue by Emmanuel-kwizera** [YogliB/svelte-fullcalendar#876]
Have you used this library inside of a svelte kit based application? I’m trying it out and not able to render it because of an error stating that Calendar is not SSR compatible.

**Comment by YogliB** [comment]
hey, thanks for reporting! 🙂 
try copying the example, then remove the `.sveltekit` folder & change the package version inside the `package.json` to `latest`.

I did exactly that and everything seems to be working.

if everything goes well, I suggest going carefully through the README for integrating FC in your project.

**Comment by YogliB** [comment]
besides that, if you could provide a reproduction repository that would make it much easier investigating the problem.
