### ISSUE TITLE
Error: Please import the top-level fullcalendar lib before attempting to import a plugin.     at vdom.js:3:11

### ISSUE THREAD

**Issue by aunumever** [YogliB/svelte-fullcalendar#900]
I am receiving the following error:

```
Error: Please import the top-level fullcalendar lib before attempting to import a plugin.
```

I've seen this issue around other repos, but nothing I do fixes the issue. Sometimes the app works fine, and then all of a sudden it will break, and will remain broken, until I comment out the calendar code and refresh.

It seems there are loading priority issues. Any thoughts on how to fix this?

These are my imports:
```
  import FullCalendar from 'svelte-fullcalendar';
  import daygridPlugin from '@fullcalendar/daygrid';
  import interactionPlugin from '@fullcalendar/interaction';
```

As far as I can tell, adding the import at top here fixes the issue, but only if it's in brackets.

```
  import('@fullcalendar/core/vdom.js');
  import FullCalendar from 'svelte-fullcalendar';
  import daygridPlugin from '@fullcalendar/daygrid';
  import interactionPlugin from '@fullcalendar/interaction';
```

**Comment by YogliB** [comment]
hey, can you try again after following the README?
and I suggest looking at [the example](https://github.com/YogliB/svelte-fullcalendar/tree/main/examples/kit) for reference.

**Comment by devShamim** [comment]
Just import @fullcalendar/core/vdom before you import svelte-fullcalendar and other fullcalendar plugins. Like this: 
`import '@fullcalendar/core/vdom';`
`import FullCalendar from 'svelte-fullcalendar';`
`import daygridPlugin from '@fullcalendar/daygrid';`

I am using this version (^2.0.0-beta.0) of svelte-fullcalendar along with **vite-4.0.1**
