### ISSUE TITLE
full calendar doesn't resize automatically

### ISSUE THREAD

**Issue by yoonheehan** [YogliB/svelte-fullcalendar#929]
full calendar using react, js or older version of this svelte-fullcalendar can be resized but
now when i resize it, it becomes like this
![image](https://user-images.githubusercontent.com/87460128/205255699-8c48fe8a-c7e1-43d6-9e59-bae7f2ee79bf.png)

the grid(or table?) width doesn't seem to move
Why is this happening?

**Comment by YogliB** [comment]
can you give a reproduction?

**Comment by novicailievski93** [comment]
Why did you close this issue @yoonheehan? Did you figure out a solution?
